vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    folders:
      uri_prefix: uploads/folders
      upload_destination: "%kernel.project_dir%/public/uploads/folders"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_remove: true
      delete_on_update: true
